#!/usr/bin/python
import stmplib

SERVER = smtplib.SMTP('smtp.server.domain')
FROM nihita.reddy@gmail.com
TO ["reddy.vikhyath@gmail.com","nihitareddy4@gmail.com"]
SUBJECT = "Hello World "
TEXT = "This message was sent with Python's smtplib."
server = smtplib.SMTP(SERVER)
server.sendmail(FROM, TO, message)
server.quit()
